### ISSUE TITLE
dataloader : load_data_nologs

### ISSUE THREAD

**Issue by rachittibrewal** [Auquan/auquan-toolbox-python#10]
https://github.com/Auquan/auquan-toolbox-python/blob/fa36d3aa30a6c1e0309c88fbec7eacbdd2f8dd42/auquanToolbox/dataloader.py#L189
I am fairly new to Auquan but while doing one of your beginner tutorial, I encountered a bug,
```python
from auquanToolbox import dataloader as dl
from __future__ import division
start = "2014-01-01"
end = "2016-12-31"
data = dl.load_data_nologs('nasdaq',['AAPL'],start,end)
prices = data['ADJ CLOSE']['AAPL']
```
tried in python2.7 on Ubuntu 18.04
The line of code referenced here seems to be the problem as lookback=2 *1.1 +10 gives a floating point number while BDay expects an int. Typecasting it to int should solve the problem.

**Comment by lackorol** [comment]
I have tried auquan also and code still throwing exception ValueError on correctly given dates. I have tried also typecasting to int which is probably the another bug but can't make it work it.

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\rolni\OneDrive\Documents\math\lib\site-packages\auquanToolbox\dataloader.py", line 166, in load_data_nologs
    raise ValueError("%s or %s is not valid date. Please check settings!"%(start, end))
ValueError: 2013-06-01 or 2016-12-31 is not valid date. Please check settings!`

**Comment by shashank-auquan** [comment]
Hi, you can try using the newer version of the toolbox: https://links.auquan.com/auquan-toolbox, if the issue persists you can create an issue in the newer repo
