### ISSUE TITLE
File "my_trading_params.py", line 40, in getDataParser     event='history') TypeError: __init__() got an unexpected keyword argument 'event'

### ISSUE THREAD

**Issue by chiju** [Auquan/auquan-toolbox-python#11]
Got error "File "my_trading_params copy.py", line 40, in getDataParser
    event='history')
TypeError: __init__() got an unexpected keyword argument 'event'"

when I changed yahoo to nse, so I think historical data is not available free for NSE, please confirm

**Comment by chiju** [comment]
Hi,
If you guys have any example in which uses NSE data for backtesting please provide the same here.

**Comment by shashank-auquan** [comment]
Hi, you can try using the newer version of the toolbox: https://links.auquan.com/auquan-toolbox, if the issue persists you can create an issue in the newer repo
