### ISSUE TITLE
auquan works on python 3? I am not able to install. It always gives error.

### ISSUE THREAD

**Issue by ERICAVN** [Auquan/auquan-toolbox-python#13]

**Comment by davidardagh** [comment]
Hey,

This is an old version of the toolbox. Here is the newest build: https://pypi.org/project/auquan-toolbox/

If you're trying to install the toolbox for a competition, please use the competition-specific toolbox. If you're having problems there, please post in the competition discussion and we'll be better able to help you.

Best,
David
