### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by zhang128** [Auquan/auquan-toolbox-python#14]
![image](https://user-images.githubusercontent.com/9532350/82494682-918b4800-9aaf-11ea-8551-598437c825ff.png)
Encounter the error while running code block 8.

**Comment by chandinijain** [comment]
This error is caused by an upgrade to Pandas that removed this function. We will address this in a future update, but from now the toolbox requires you use pandas version .24.

you can do this by adding `!pip install pandas==0.24.2 --user` to your notebook to version lock pandas
