### ISSUE TITLE
Cannot Import auquantoolbox or auquan-Toolbox

### ISSUE THREAD

**Issue by swlokzk** [Auquan/auquan-toolbox-python#15]
after I already Install the pip install auquan-toolbox and it's successfully done
but I still can't import any lib of the toolbox
please check

-----------------------------------------------
ModuleNotFoundError: No module named 'auquantoolbox'

-----------------------------------------------
  File "<ipython-input-33-06781e392334>", line 1
    import auquan-toolbox
                 ^
SyntaxError: invalid syntax

**Comment by chandinijain** [comment]
you need to change it to `import backtester`
