### ISSUE TITLE
Error installing: cannot import name 'NavigationToolbar2TkAgg' from 'matplotlib.backends.backend_tkagg'

### ISSUE THREAD

**Issue by danilodn** [Auquan/auquan-toolbox-python#16]
File "C:\Users\danil\auquan-toolbox-python\auquanToolbox\resultviewer.py", line 6, in <module>
    from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg, NavigationToolbar2TkAgg

ImportError: cannot import name 'NavigationToolbar2TkAgg' from 'matplotlib.backends.backend_tkagg' (C:\Users\danil\Anaconda\envs\py27\lib\site-packages\matplotlib\backends\backend_tkagg.py)

**Comment by danilodn** [comment]
The error occurs while trying to install through pip install -U auquanToolbox and python setup.py install.
Installing through pip install auquan-toolbox works fine.

**Comment by chandinijain** [comment]
` auquan_toolbox` is the right package.` auquanToolbox `is a different, old package which is now deprecated
