### ISSUE TITLE
Error while installing aquan toolbox :   error: file '/tmp/pip-build-yMxIQu/aquanToolbox/TradingStrategyTemplate' does not exist

### ISSUE THREAD

**Issue by pranshubhatnagar** [Auquan/auquan-toolbox-python#6]
On doing a simple pip install -U aquanToolbox on my Ubuntu 16.04 I get the following error. I have all requirements up to date.

Collecting aquanToolbox
  Using cached aquanToolbox-1.1.0.tar.gz
Requirement already up-to-date: pandas in /usr/local/lib/python2.7/dist-packages (from aquanToolbox)
Requirement already up-to-date: numpy in /home/pranshu/.local/lib/python2.7/site-packages (from aquanToolbox)
Requirement already up-to-date: matplotlib in /usr/local/lib/python2.7/dist-packages (from aquanToolbox)
Requirement already up-to-date: pytz>=2011k in /usr/local/lib/python2.7/dist-packages (from pandas->aquanToolbox)
Requirement already up-to-date: python-dateutil in /usr/local/lib/python2.7/dist-packages (from pandas->aquanToolbox)
Requirement already up-to-date: cycler>=0.10 in /usr/local/lib/python2.7/dist-packages (from matplotlib->aquanToolbox)
Requirement already up-to-date: functools32 in /usr/local/lib/python2.7/dist-packages (from matplotlib->aquanToolbox)
Requirement already up-to-date: six>=1.10 in /usr/lib/python2.7/dist-packages (from matplotlib->aquanToolbox)
Requirement already up-to-date: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=1.5.6 in /usr/local/lib/python2.7/dist-packages (from matplotlib->aquanToolbox)
Requirement already up-to-date: subprocess32 in /usr/local/lib/python2.7/dist-packages (from matplotlib->aquanToolbox)
Building wheels for collected packages: aquanToolbox
  Running setup.py bdist_wheel for aquanToolbox ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-yMxIQu/aquanToolbox/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpvyOWFppip-wheel- --python-tag cp27:
  
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/pythonToolbox
  copying pythonToolbox/version.py -> build/lib.linux-x86_64-2.7/pythonToolbox
  copying pythonToolbox/dataloader.py -> build/lib.linux-x86_64-2.7/pythonToolbox
  copying pythonToolbox/toolbox.py -> build/lib.linux-x86_64-2.7/pythonToolbox
  copying pythonToolbox/__init__.py -> build/lib.linux-x86_64-2.7/pythonToolbox
  copying pythonToolbox/resultviewer.py -> build/lib.linux-x86_64-2.7/pythonToolbox
  copying pythonToolbox/metrics.py -> build/lib.linux-x86_64-2.7/pythonToolbox
  running egg_info
  writing requirements to aquanToolbox.egg-info/requires.txt
  writing aquanToolbox.egg-info/PKG-INFO
  writing top-level names to aquanToolbox.egg-info/top_level.txt
  writing dependency_links to aquanToolbox.egg-info/dependency_links.txt
  warning: manifest_maker: standard file '-c' not found
  
  reading manifest file 'aquanToolbox.egg-info/SOURCES.txt'
  writing manifest file 'aquanToolbox.egg-info/SOURCES.txt'
  running build_scripts
  creating build/scripts-2.7
  error: file '/tmp/pip-build-yMxIQu/aquanToolbox/TradingStrategyTemplate' does not exist
  
  ----------------------------------------
  Failed building wheel for aquanToolbox
  Running setup.py clean for aquanToolbox
Failed to build aquanToolbox
Installing collected packages: aquanToolbox
  Running setup.py install for aquanToolbox ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-yMxIQu/aquanToolbox/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-cwW7Y9-record/install-record.txt --single-version-externally-managed --compile:
    
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/pythonToolbox
    copying pythonToolbox/version.py -> build/lib.linux-x86_64-2.7/pythonToolbox
    copying pythonToolbox/dataloader.py -> build/lib.linux-x86_64-2.7/pythonToolbox
    copying pythonToolbox/toolbox.py -> build/lib.linux-x86_64-2.7/pythonToolbox
    copying pythonToolbox/__init__.py -> build/lib.linux-x86_64-2.7/pythonToolbox
    copying pythonToolbox/resultviewer.py -> build/lib.linux-x86_64-2.7/pythonToolbox
    copying pythonToolbox/metrics.py -> build/lib.linux-x86_64-2.7/pythonToolbox
    running egg_info
    writing requirements to aquanToolbox.egg-info/requires.txt
    writing aquanToolbox.egg-info/PKG-INFO
    writing top-level names to aquanToolbox.egg-info/top_level.txt
    writing dependency_links to aquanToolbox.egg-info/dependency_links.txt
    warning: manifest_maker: standard file '-c' not found
    
    reading manifest file 'aquanToolbox.egg-info/SOURCES.txt'
    writing manifest file 'aquanToolbox.egg-info/SOURCES.txt'
    running build_scripts
    creating build/scripts-2.7
    error: file '/tmp/pip-build-yMxIQu/aquanToolbox/TradingStrategyTemplate' does not exist
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-yMxIQu/aquanToolbox/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-cwW7Y9-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-yMxIQu/aquanToolbox/

**Comment by pranshubhatnagar** [comment]
So I downloaded the git repo and then ran setup.py. After which I was was asked to install python-tk. After installing that, the download seems to work fine (including the pip install). Perhaps python-tk is also a required dependency?

**Comment by chandinijain** [comment]
Hey,

You tried installing an old mis-spelt version that we never removed.

The correct version is `pip install -U auquanToolbox` 
(not aquanToolbox, notice the spelling of "auquan") :)

**Comment by Shivam-117** [comment]
<img width="1148" alt="screen shot 2018-08-11 at 12 39 53 pm" src="https://user-images.githubusercontent.com/42290802/43989255-19b7868a-9d64-11e8-8aa7-0f4fbd14d758.png">
Can't seem to install auquanToolbox.
Help!

**Comment by nkunchavaram** [comment]
`Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-xm7q3l3d/auquanToolbox/`

I tried to upgrade `pip` and `setup_tools` prior to install, but no luck.
