### ISSUE TITLE
`python my_trading_params.py` results in "KeyError: nan"

### ISSUE THREAD

**Issue by bhavishyagopesh** [Auquan/auquan-toolbox-python#8]
is it supposed to behave this way?(may becoz of incomplete template)
BTW this is about the new version ([on bitbucket](https://bitbucket.org/auquan/auquantoolbox/wiki/browse/)), couldn't find thwe issue tracker there...

**Comment by TeamAuquan** [comment]
You're supposed to fill in the function before my_trading_params.py works.
https://bitbucket.org/auquan/auquantoolbox/src/master/meanreversion_trading_params.py
this is a complete file.
Here's the issues tracker
https://bitbucket.org/auquan/auquantoolbox/issues

**Comment by shashank-auquan** [comment]
Hi, you can try using the newer version of the toolbox: https://links.auquan.com/auquan-toolbox, if the issue persists you can create an issue in the newer repo
