### ISSUE TITLE
Support for derivatives?

### ISSUE THREAD

**Issue by ChillarAnand** [Auquan/auquan-toolbox-python#9]
Aquan toolbox is good for linear instruments(stocks/indices). But this is not sufficient to backtest options/futures strategies. Are there any plans to provide support for derivatives?

**Comment by shashank-auquan** [comment]
Hi, you can try using the newer version of the toolbox: https://links.auquan.com/auquan-toolbox, if the issue persists you can create an issue in the newer repo
